"""Criar a tabela Matricula

Revision ID: b940eb92bdd9
Revises: 0f61dfd87349
Create Date: 2026-09-27 17:22:23.971660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b940eb92bdd9'
down_revision: Union[str, Sequence[str], None] = '0f61dfd87349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
